- name: Modify Greeting
  hosts: all
  become: true

  tasks:
    # - name: Check Connectivity
    #   ansible.builtin.ping: 
    - name: Copy App File
      ansible.builtin.lineinfile:
        path: src/App.js
        search_string: 'World'
        line: DevOps